### ISSUE TITLE
Install without pre-defined bundles?

### ISSUE THREAD

**Issue by basicmaster** [pabigot/pyxb#121]
Using `pip install pyxb`, also all the pre-defiend bundles are installed, which represent more than 90% of the package size - and which are not needed in my case. To optimize the size of this package while building a Docker image, I currently just delete `/lib/python2.7/site-packages/pyxb/bundles` to free about 40 MB. But I wonder if there is some way to already opt-out to install these bundles during package setup.

**Comment by pabigot** [comment]
Until 1.1.4 (15 Jun 2012) the bundles were packaged separately.  At that point pypi/distutils stopped allowing the back doors I used to manage the dependencies, so everything got put into one package.

The post-install remove step you have is the best solution now.

**Comment by basicmaster** [comment]
Ah, I see. So I will continue with the current way to shrink the size. Thank you!
