### ISSUE TITLE
please add --prefix to setup.py, with /usr/local as default

### ISSUE THREAD

**Issue by anordal** [pabigot/pyxb#29]
I am always a bit surprised by software that wants to install itself to /usr instead of /usr/local, but most will accept the --prefix option.

However, this didn't work:
 ./setup.py --prefix=/usr/local install

I like to keep stuff I download from the internet separate from my package manager's installed files.

I think /usr/local is a saner default than /usr — /usr/local is supposedly for sysadmins, /usr is for distro package maintainers only.

**Comment by pabigot** [comment]
PyXB uses the distutils/setuptools defaults as they existed when the system was created.  I'll look into whether the current version supports a prefix option that's somehow being bypassed.

**Comment by anordal** [comment]
Okay, so this is an upstream issue then.

Anyway, this works:
 ./setup.py install --prefix=/usr/local

The parameter order is actually documented in the --help text:
 usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

Though the parameter order wasn't super-intuitive to me
