### ISSUE TITLE
The How To Use it guide does not list Python 3.x (x >= 1) support

### ISSUE THREAD

**Issue by skiwi2** [pabigot/pyxb#36]
On http://pyxb.sourceforge.net/overview_how.html it looks like it says that Python 3.x is not supported at all, however in the changelog it says that it works for Python 3.x (x >=1).

**Comment by pabigot** [comment]
Good catch; that part of the documentation wasn't updated.  Python 3 support was added in [PyXB 1.2.4](http://pyxb.sourceforge.net/releases.html#releases), earlier than expected.

Ticket remains open until documentation updated in a released version.
