### ISSUE TITLE
pyxbgen: Problem with paths containing dots

### ISSUE THREAD

**Issue by reet-** [pabigot/pyxb#49]
Hi,

First of all thanks for pyxb!

I have encountered a problem with the way pyxbgen handles filesystem paths containing dots. Consider the following command:

    $ scripts/pyxbgen -u /tmp/test.dir/config.xsd -m /tmp/test.dir/generated/config

`config.xsd` can be any schema.

Instead of creating the requested `/tmp/test.dir/generated/config.py` module, a file named `/tmp/test/dir/generated/config.py` is created. I traced the problem to the `split('.')` operations in `generate.py` but I had trouble understanding the intention of the code.

Thanks!
reet

**Comment by pabigot** [comment]
The `-m` option specifies the Python module name, not the output file name.

Take a look at [these pyxbgen options](http://pyxb.sourceforge.net/pyxbgen_cli.html#configuring-bindings).  I think you want `--binding-root`:

    scripts/pyxbgen -u /tmp/test.dir/config.xsd -m config --binding-root /tmp/test.dir/generated

Let me know whether that solves the problem for you.

**Comment by reet-** [comment]
Hi,

Thanks for the fast reply. Indeed, the `--binding-root` option fixes the issue. It is a bit strange though that our code worked using `-m` with an absolute path (if this option specifies the module name).

Closing the issue, thanks!
