### ISSUE TITLE
Potential Python 3 Issue.

### ISSUE THREAD

**Issue by chaosape** [pabigot/pyxb#52]
`transitionSortKey` in generate.py can return a tuple containing `None` if `st` is `None`. On line 340 in generate.py transitions are sorted using `transitionSortKey`; python 2 would engage in some voodoo to evaluate mistyped inequalities, python 3 does not allow this.

**Comment by pabigot** [comment]
Thanks for reporting this.  I suspect that substituting zero in that case would handle it, but if the sort key is ever used to detect that a transition lacks a consuming state operation will have to be given a comparison function that replicates the concept of a bottom value.

The (different) sort key for schema order has a comment noting that this feature of Python 3 had been taken into account.

**Comment by pabigot** [comment]
To ensure uniqueness the substitution value should be -1.
