### ISSUE TITLE
Issue when generating opengis bundle

### ISSUE THREAD

**Issue by jlmenut** [pabigot/pyxb#54]
Hello,

I'm trying to generate the opengis bundle as described here http://pyxb.sourceforge.net/bundles.html#opengis

but I got an error message : 
[error.txt](https://github.com/pabigot/pyxb/files/270817/error.txt)

 I'm using pyxb 1.2.4 from Pypi.

Thanks

**Comment by pabigot** [comment]
I don't know what PyPI installs provide.  The error suggests you don't have the xlink bindings from the common bundle.  Try running these commands then re-generating the opengis bindings.

    cd ${PYXB_ROOT}
    pyxb/bundles/common/scripts/genbind

**Comment by jlmenut** [comment]
thanks, I actually reinstalled pyxb from sources since, and it worked fine
