### ISSUE TITLE
No official release since 2014

### ISSUE THREAD

**Issue by cmorse** [pabigot/pyxb#56]
There hasn't been an official release of pyxb since 10/2014. I recently encountered a bug in 1.2.4, which is not present in the unreleased version of the code (1.2.5-DEV). Since it has been so long since 1.2.4 was released, a new release would greatly be appreciated.

**Comment by pabigot** [comment]
How greatly appreciated?

Yeah, I agree it should be done.  There's a lot of effort in a release (checking under various versions of Python, updating the bundles to latest schemas, reviewing the tickets to see if something's important enough to block the release, etc.) but a goal of at least one release per year is reasonable.  2015 was missed, and it still won't happen until September or October 2016, but I'll try to find time so it can be done by then.

**Comment by cmorse** [comment]
Appreciation beyond words :wink:.

Thanks! I understand it takes work to make a release. I'll keep an eye out for it.

**Comment by pabigot** [comment]
1.2.5 is released.
