### ISSUE TITLE
examples/manual/demo4c1.py does not work due to pyxb.BIND for items

### ISSUE THREAD

**Issue by dotzhou** [pabigot/pyxb#59]
1. When I play with the examples for PYXB, I failed to get the "examples/manul/demo4c1.py".

`
from __future__ import print_function
import pyxb
import po4
import address
import pyxb.binding.datatypes as xs

po = po4.purchaseOrder(orderDate=xs.date(1999, 10, 20))
po.shipTo = address.USAddress('Alice Smith', '123 Maple Street', 'Anytown', 'AK', 12341)
po.billTo = address.USAddress('Robert Smith', '8 Oak Avenue', 'Anytown', 'AK', 12341)
po.items = pyxb.BIND(pyxb.BIND('Lapis necklace', 1, 99.95, partNum='833-AA'),
                     pyxb.BIND('Plastic necklace', 4, 3.95, partNum='833-AB'))
                
print(po.toxml("utf-8"))
`

It failed at        po.items BIND

2. The error message is below

  File "demo4c1.py", line 11, in <module>
    pyxb.BIND('Plastic necklace', 4, 3.95, partNum='833-AB'))
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 98, in __setattr__
    return super(_TypeBinding_mixin, self).__setattr__(name, value)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/content.py", line 1043, in set
    value = self.__elementBinding.compatibleValue(value, is_plural=self.isPlural())
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 1643, in compatibleValue
    return self.typeDefinition()._CompatibleValue(value, **kw)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 421, in _CompatibleValue
    return value.createInstance(cls.Factory, **kw)
  File "/opt/lib/python2.7/site-packages/pyxb/__init__.py", line 106, in createInstance
    return factory(*self.__args, **kw)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 305, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 691, in _DynamicCreate
    return ctor(*args, **kw)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2108, in __init__
    self.extend(args, _from_xml=from_xml, _location=location)
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2593, in extend
    [ self.append(_v, **kw) for _v in value_list ]
  File "/opt/lib/python2.7/site-packages/pyxb/binding/basis.py", line 2548, in append
    raise pyxb.UnrecognizedContentError(self, self.__automatonConfiguration, value, location)
pyxb.exceptions_.UnrecognizedContentError: Invalid content <pyxb.BIND object at 0x7fb64615be90> (expect {URN:purchase-order}item)

**Comment by dotzhou** [comment]
$ echo $PYTHONPATH
:/opt/lib/python2.7/site-packages/

$ pyxbgen --version
pyxbgen from PyXB 1.2.5

$ python --version
Python 2.7.12



The contents of schema of "po4.xsd", I believe the "demo4.sh" and "demo4b.sh" are incorrect?
They did not generate "po4.xsd" actually.

$ cat po4.xsd 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   targetNamespace="URN:purchase-order"
   xmlns:tns="URN:purchase-order"
   xmlns:address="URN:address"
   elementFormDefault="qualified">
  <xsd:import namespace="URN:address" schemaLocation="nsaddress.xsd"/>
  <xsd:element name="purchaseOrder" type="tns:PurchaseOrderType"/>
  <xsd:element name="comment" type="xsd:string"/>
  <xsd:complexType name="PurchaseOrderType">
    <xsd:sequence>
      <xsd:element name="shipTo" type="address:USAddress"/>
      <xsd:element name="billTo" type="address:USAddress"/>
      <xsd:element ref="tns:comment" minOccurs="0"/>
      <xsd:element name="items"  type="tns:Items"/>
    </xsd:sequence>
    <xsd:attribute name="orderDate" type="xsd:date"/>
  </xsd:complexType>
  <xsd:complexType name="Items">
    <xsd:sequence>
      <xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="productName" type="xsd:string"/>
            <xsd:element name="quantity">
              <xsd:simpleType>
                <xsd:restriction base="xsd:positiveInteger">
                  <xsd:maxExclusive value="100"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="USPrice"  type="xsd:decimal"/>
            <xsd:element ref="tns:comment"   minOccurs="0"/>
            <xsd:element name="shipDate" type="xsd:date" minOccurs="0"/>
          </xsd:sequence>
          <xsd:attribute name="partNum" type="tns:SKU" use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:simpleType name="SKU">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\d{3}-[A-Z]{2}"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

$

**Comment by dotzhou** [comment]
@pabigot :+1: 

If you could help, that is great

I need to successfully build with all examples mentioned at manual.

Thanks to you in advance.

**Comment by pabigot** [comment]
This is a bug introduced two years ago when the representation of `xsd:decimal` converted to use Python's [decimal.Decimal](https://docs.python.org/2/library/decimal.html#decimal-objects) class.  The value 99.95 can't be represented exactly as a float, so does not compare equal to the value passed through `pyxb.BIND`.  A patch is incoming, but it won't be in another release until 1.2.5 gets more road time.

**Comment by dotzhou** [comment]
Dear Peter:

Great thanks for your quick response and efforts.

Good work and good attitude.

Best wishes,
