### ISSUE TITLE
How to represent a nillable Double with a Pyxb type?

### ISSUE THREAD

**Issue by dotzhou** [pabigot/pyxb#65]
Dear Peter @pabigot:

Could I ask more question?

The temperature value should be a "double", but also can be left as empty.
It should be a nillable double type, as below:

               <geo:temperature xsi:nil="true"/>
or 
              <geo:temperature> 22.2 </geo:temperature>

How to represent a nillable double with a proper Pyxb type?

Probably anyType() or anySimpleType()?

But how to added its nillable attribute to it?

        anySimpleType(xsd.nil="true")?

Any tips or clues?

Best wishes,

Ted

**Comment by pabigot** [comment]
There are examples in the source tree unit tests, in particular [this one for core nil support](https://github.com/pabigot/pyxb/blob/next/tests/drivers/test-xsi-nil.py), [this one for construction from xml](https://github.com/pabigot/pyxb/blob/next/tests/trac/test-trac-0200.py), or [this one for an annotated nil](https://github.com/pabigot/pyxb/blob/next/tests/trac/test-trac-0047.py).
