### ISSUE TITLE
foo.Namespace.setPrefix('') gives wrong result

### ISSUE THREAD

**Issue by nowox** [pabigot/pyxb#66]
I would like to get rid of the `ns1` prefix so I set the prefix to an empty string. Instead of removing the prefix completely, pyxb adds empty prefixes: 

     <:foo></:foo>

**Comment by pabigot** [comment]
That would be undefined behavior.  To remove the prefix give your document a default namespace.

    import myns
    import pyxb.utils.domutils
    pyxb.utils.domutils.BindingDOMSupport.SetDefaultNamespace(myns.Namespace)

**Comment by nowox** [comment]
Good to learn that. It would be nice to find it on the documentation.

**Comment by pabigot** [comment]
Resolution would be that PyXB should reject the attempt to set an empty string prefix.
