### ISSUE TITLE
Include support for XML regex expressions like "regex|"

### ISSUE THREAD

**Issue by bushmanov** [pabigot/pyxb#69]
When PyXB processes XSD patterns that include expressions like `"regex|"`, e.x. `"[0-9]{9}|"`, the result is not what should be expected according to XML regex definitions given here https://www.w3.org/TR/xmlschema-2/#regexs  

Namely, the above mentioned regex in PyXB accepts anything rather than only allowing 9 digits or empty string (for more details see this question on [stackoverflow](http://stackoverflow.com/questions/41103495/is-this-xsd-regex-makes-sense-and-or-posix-compliant) and this [example](https://sourceforge.net/p/pyxb/discussion/956708/thread/eea3e43a/))

A temporary workaround for this issue could be to re-write the regex in XSD as `"([0-9]{9}|)?"`.

**Comment by pabigot** [comment]
Thanks for the report.  You can cherry-pick the patch; the next PyXB release is some months away.
