### ISSUE TITLE
[BUG] nonNegativeInteger type implementation assumes 0 value on empty tag

### ISSUE THREAD

**Issue by kozmaz87** [pabigot/pyxb#71]
It should not pass validation if:
  
    <myelem></myelem>

and myelem is of type="nonNegativeInteger"

**Comment by pabigot** [comment]
Confirmed.  The problem probably exists in all types that subclass Python built-in scalars.  No estimate on when a patch will be available.

**Comment by kozmaz87** [comment]
I am trying to wrap my head around this with all the facets and _nil and whatnot to understand where to apply a fix to PR back. Unfortunately the usual subclass and _ConvertArguments_vx even with super call makes everything break in obscure unexpected ways. Very peculiar.
