### ISSUE TITLE
What this regex could mean?

### ISSUE THREAD

**Issue by bushmanov** [pabigot/pyxb#74]
Can somebody explain me please, what symbols the following `xml` regex taken from `xsd` might include? I am interested in the non-digit part. The regex was generated by XMLSpider:

```
    [0-9' '\-/.]
```

**Comment by pabigot** [comment]
I don't have any idea what it was intended to recognize, but from inspection I would expect it it to recognize the same language as `[.]`, which would be anything except newline and carriage return.
