### ISSUE TITLE
Remove GPL code from PyXB releases

### ISSUE THREAD

**Issue by rvs** [pabigot/pyxb#77]
While all of PyXB code is now available under Apache License v2, there's a single file in the release tarballs that is licensed under GPL: https://github.com/pabigot/pyxb/blob/next/doc/extapi.py 

This, unfortunately, makes an overall release of PyXB something other that Apache License v2.

Would it be possible to either re-license this file, re-write it from scratch or at least exclude it from your release artifacts so that we, downstream, can consume it in fully Apache License v2 fashion?

**Comment by pabigot** [comment]
Thanks for bringing that to my attention.  It's necessary only for linking to the API documentation; it certainly could be excluded from the release, though doing so would prevent anybody from building that documentation.  I'm not interested in trying to rewrite it.  Before the next release I'll see if there's anything in current versions of sphinx that could be used instead to simplify the link.

**Comment by rvs** [comment]
Thank you for considering this. Without this here's what we have to do downstream: https://github.com/apache/incubator-madlib/blob/master/src/patch/PyXB.sh

**Comment by rvs** [comment]
@pabigot great to see the change landing! Quick question: when do you think can we expect to see 1.2.6 out?

**Comment by pabigot** [comment]
PyXB's been doing annual fall releases for a while; September 18th seems to have some tradition behind it, but I'll aim for the first week of September assuming no new blocking defects are reported this month.

**Comment by pabigot** [comment]
@rvs PyXB 1.2.6 has been released.
