### ISSUE TITLE
automaton error with no component

### ISSUE THREAD

**Issue by pabigot** [pabigot/pyxb#79]
[This question](https://sourceforge.net/p/pyxb/discussion/956708/thread/616cfbb9/?limit=25#8d87) may involve [this schema](https://github.com/ibm-datapower/datapower-configuration-manager/blob/master/tests-deploy.ant/wsdls_xsds/xml-mgmt.xsd) which has this content:

    <xsd:complexType name="ActionAddSelTestEntry">
      <xsd:sequence>
        <xsd:element name="filler" minOccurs="0" maxOccurs="0" />
      </xsd:sequence>
    </xsd:complexType>

The `filler` element has no component in the content model, so references to it fail.

**Comment by stormbard** [comment]
@pabigot That is a version of the schema I was using.
