### ISSUE TITLE
I'm having issues

### ISSUE THREAD

**Issue by c0h1b4** [pabigot/pyxb#82]
I am trying to generate a py class from the xsd in the gist: https://gist.github.com/c0h1b4/cd6aeccf0208d64f863a943a40b4c732

I am getting the following error:

pyxb.exceptions_.SchemaValidationError: Value constraint on element {http://www.tce.sp.gov.br/audesp/xml/tagcomum}TipoTAditivoOutros with non-simple content

The specific item is this:

```
    <xs:complexType name="TAditivoOutros_t">
      <xs:sequence>
	        <!-- 14 - Outros  -->
         <xs:element name="TipoTAditivoOutros" fixed="14" minOccurs="1" maxOccurs="1"/>
         <xs:element name="DescricaoTAditivoOutros" type="tag:StringAte100_t" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
```

Anyone can help me on generating the py file for this XSD?

Thanks!
David

**Comment by pabigot** [comment]
The schema specifies that the simple type `TipoTAditivo_t` can accept only integral values in the range 1 through 13, but the element `TipoTAditivoOutros` which has content of that type can accept only 14 as its value.  This is inconsistent and the schema is invalid.

**Comment by pabigot** [comment]
The schema in that gist also depends on this one:

    <xs:import namespace="http://www.tce.sp.gov.br/audesp/xml/generico"
      schemaLocation="../generico/AUDESP_TIPOSGENERICOS_2017_A.XSD"/>

which I can't access.  If I don't have the full set of schemas I can't reproduce the problem and suggest a fix.

**Comment by c0h1b4** [comment]
Sorry.

The other schema (AUDESP_TIPOSGENERICOS_2017_A.XSD) is here:

https://gist.github.com/c0h1b4/38ea6777cb74ffdc0ce44145454d0543

**Comment by pabigot** [comment]
Thanks; that helps a lot.

My comment was not quite correct.  It appears that schema defines a simple type with restricted values, but the real problem is the `Outros` element on line 1738 provides a default (fixed) value but doesn't provide the type that it has to conform to:

    <xs:element name="TipoTAditivoOutros" fixed="14" minOccurs="1" maxOccurs="1"/>

The smallest change that works is:

    <xs:element name="TipoTAditivoOutros" fixed="14" type="xs:int" minOccurs="1" maxOccurs="1"/>

which has some precedence in the schema, or for type correctness add:

         <xs:enumeration value="14"/>
         

to `TipoTAditivo_t` and use:

    <xs:element name="TipoTAditivoOutros" fixed="14" type="tag:TipoTAditivo_t" minOccurs="1" maxOccurs="1"/>

**Comment by pabigot** [comment]
Setting `value="14"` would work because it would remove the schema requirement that a conforming instance of the element have the value 14.  It's essentially equivalent to just removing the value constraint entirely.
