### ISSUE TITLE
Limit of non deterministic content is not configurable

### ISSUE THREAD

**Issue by AliceAlbano** [pabigot/pyxb#83]
When trying to parse a xml with pyxb, I had this issue: `ContentNondeterminismExceededError: Nondeterminism exceeded validating `

The xml that I was trying to parse was indeed non deterministic, but I could not change it. Maybe it could be better if the users were able to set this limit to the value they want to use (it is 20 in the code).

**Comment by pabigot** [comment]
Actually, it is configurable there's just no specific or documented API for it.  See [this test](https://github.com/pabigot/pyxb/blob/next/tests/trac/test-trac-0172.py#L40) that changes it for a specific instance.

You might also do something like this:

    import pyxb.binding.content
    pyxb.binding.content.AutomatonConfiguration.PermittedNondeterminism += 5;

**Comment by pabigot** [comment]
Absent feedback I'm considering that the current approaches for controlling nondeterminism are sufficient.
