### ISSUE TITLE
Unexpected results from GDSClassMapping when using complexTypes 

### ISSUE THREAD

**Issue by chrislgunning** [pabigot/pyxb#89]
[test_case_generateDS.zip](https://github.com/pabigot/pyxb/files/1369339/test_case_generateDS.zip)
The "error" that we are seeing occurs when:
(a) a simple element is is initially used to associate a tag name (Data) with a complex type (DataMessage) in an XSD schema,
(b) in the same schema, another complex type (Measurement) contains a sequence that happens to be named (Data) as well and maps to a different complex type (DataMessageDetails).

The class mapping we are expecting is:

GDSClassesMapping = {
    'Data': DataMessage,
    'Details': DataMessageDetails,
    'Measurement': CategoryOne,
}
 
--but-- the ACTUAL result is:

GDSClassesMapping = {
    'Data': DataMessageDetails,
    'Details': DataMessageDetails,
    'Measurement': CategoryOne,
}

We are seeing many more erroneous mappings. The XSD and generated bindings are attached. Please advise if this if this a bug or if a usage flag can be easily used to resolve.

Thanks!
Christin  Gunning

[test_case_generateDS.zip](https://github.com/pabigot/pyxb/files/1369342/test_case_generateDS.zip)

**Comment by pabigot** [comment]
pyxbgen -u generic_schema.xsd -m gs

generates a diagnostic: 

    Expected restriction or extension as sole child of complexContent in DataMessage

because the schema itself is ill-formed.  [This service](http://www.utilities-online.info/xsdvalidation) may be useful to you.

In practice, your examples show you're using generateDS, not PyXB.  Please send the issue to them (probably after correcting your schema).
