### ISSUE TITLE
toDOM() node not supported.

### ISSUE THREAD

**Issue by rvalle** [pabigot/pyxb#92]
Hi!

I am trying to deal with anyType nodes that I have in my XML schemas I am dealing with.

Those nodes, represent an XML fragment that can be anything. I am trying to retrieve them as DOM using the function toDOM(), however, I get the following exception:

```
ValueError: ('DOM node not supported in clone', <DOM CDATASection node "u'x86_64'">)
```
It seems to be related to an element like this: ```<!CDATA[86_64]>```

I generated this binding instance form DOM, there should not be any problem in getting back the DOM of a sub-tree.

Is there any special reason why this kind of node cannot be created?

**Comment by pabigot** [comment]
As best I can tell none of PyXB's supported DOM capabilities preserve CDATASection nodes: they're always converted into some more primitive type based on the schema.  So the code that converts them back from instances to DOM elements doesn't handle that node type.

If you provide a minimal example of a schema, document, and code that reproduces the problem (construct the DOM from the document, then construct the instance from the DOM) I'll see what it'll take to fix it.  You can use [tests/pyxb/test-cdata.py]( https://github.com/pabigot/pyxb/blob/next/tests/pyxb/test-cdata.py) as a template.

**Comment by rvalle** [comment]
I was assuming that PyXB was broken for CDATA at some point, or maybe in the specific case of anyType document fragment.

So, I forked PyXB and started working on a test to reproduce issue before attempting the fix.

You can check it here: https://github.com/rvalle/pyxb/commit/967f03e16eb247cf60d1644d10fb8b27b73271b0

At first this unit test works, but I am comparing with my real life case.
I and tracing execution in the function domutils._deepclone

And I see the following differences:
- In the working test case above: node.nodeType is 3, and node type is <pyxb.utils.saxdom.Tex>
- In the failing case: node.nodeType is 4 and the node type is CDATASection: <DOM CDATASection>

I think the problem is happening because I created the binding using CreateFromDOM. Does it make any sense?

I will try to test further.

**Comment by rvalle** [comment]
Yes, I can now reproduce the issue if I pass the document via DOM

this unit test reproduces the problem: https://github.com/rvalle/pyxb/commit/ae9938547006443275098320b41e491b7b1cadda

**Comment by pabigot** [comment]
@rvalle Thanks.  Please pull from the [issue-92](/pabigot/pyxb/tree/issue-92) branch where there's a proposed fix.  If this works for you I'll squash it with the test case and bring it into next.  In particular if you encounter a case where the content should *not* be text, let me know.

**Comment by rvalle** [comment]
@pabigot yes, it does work for both the test and the original code that caused the issue.
I merged your fix with the test and pulled for your convenience.
