### ISSUE TITLE
MixedContentError in anyType element contents

### ISSUE THREAD

**Issue by rvalle** [pabigot/pyxb#96]
We have an XSD that defines several anyType elemntes. We are finding several samples of MixedContentErrors related to content inside the anyType document fragment.

I think the problem happens when the elements inside the anyType section are named like elements defined somewhere else in the XSD.

I wonder whether this is the expected behaviour, or an issue in PyXB.

Here are XML samples: 
https://github.com/OpenNebula/addon-pyone/blob/master/tests/ci/test_issue_006_data/vm_04.xml
https://github.com/OpenNebula/addon-pyone/blob/master/tests/ci/test_issue_006_data/vm_02.xml
And here are the XSD:
https://github.com/OpenNebula/addon-pyone/tree/master/pyone/xsd

the issue was originally reported at: https://github.com/OpenNebula/addon-pyone/issues/6

**Comment by pabigot** [comment]
I'm really not going to try to figure out a problem with mixed content from almost 2000 lines of schema spread among 28 files.  If you can provide a standalone reproducing case I'll try to take a look at it.

**Comment by rvalle** [comment]
Probably best if I produce a test case. will do.

**Comment by rvalle** [comment]
@pabigot, I managed to reproduce with really minimal XSD/XML.
Note that removing the VROUTER element declararion makes it work.

**Comment by pabigot** [comment]
While `USER_TEMPLATE` being declared as `anyType` does allow it to contain mostly arbitrary content, part of that content is an element that has content restrictions that are not satisfied.  I don't believe the relaxation on the outer level type relaxes validation for recognized content within the type.  xmllint also diagnoses this as an error; see below.

If the `VROUTER` stanza in the XML is renamed `VOUTER` it validates under xmllint, and PyXB handles it correctly with the expected:

    WARNING:pyxb.binding.basis:Unable to convert DOM node {http://opennebula.org/XMLSchema}VOUTER at <unknown>[5:4] to binding

If the `VROUTER` element declaration is modified to allow mixed content and make `ID` optional, it also works.

If you have another example that doesn't use a defined element incorrectly, or can cite an authority that rules differently than xmllint, we can revisit this, otherwise I'm ruling this non-discrepant.

    lilith[21]$ cat /tmp/h.xsd 
    <?xml version="1.0" encoding="UTF-8"?>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
      targetNamespace="http://opennebula.org/XMLSchema" xmlns="http://opennebula.org/XMLSchema">
      <xs:element name="VROUTER">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ID" type="xs:integer"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="VM">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="ID" type="xs:integer"/>
            <xs:element name="USER_TEMPLATE" type="xs:anyType"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    lilith[22]$ cat /tmp/h.xml 
    <?xml version="1.0" encoding="UTF-8"?>
    <VM xmlns="http://opennebula.org/XMLSchema">
      <ID>4010</ID>
      <USER_TEMPLATE>
        <VROUTER><![CDATA[yes]]></VROUTER>
      </USER_TEMPLATE>
    </VM>
    lilith[23]$ xmllint --valid --schema /tmp/h.xsd /tmp/h.xml 
    /tmp/h.xml:2: validity error : Validation failed: no DTD found !
    <VM xmlns="http://opennebula.org/XMLSchema">
                                               ^
    <?xml version="1.0" encoding="UTF-8"?>
    <VM xmlns="http://opennebula.org/XMLSchema">
      <ID>4010</ID>
      <USER_TEMPLATE>
        <VROUTER><![CDATA[yes]]></VROUTER>
      </USER_TEMPLATE>
    </VM>
    /tmp/h.xml:5: element VROUTER: Schemas validity error : Element '{http://opennebula.org/XMLSchema}VROUTER': Character content other than whitespace is not allowed because the content type is 'element-only'.
    /tmp/h.xml:5: element VROUTER: Schemas validity error : Element '{http://opennebula.org/XMLSchema}VROUTER': Missing child element(s). Expected is ( {http://opennebula.org/XMLSchema}ID ).
    /tmp/h.xml fails to validate

**Comment by rvalle** [comment]
Yes, it makes sense.
anyType does not  mean that elements added there can break the existing schemas.
The product I am integrating with makes a strange use of schemas, I think. They use each of this elements as a complete separate schema, and even thou they use xmllint for unit testing they don't get the errors because of it.
I will have to mimic that behaviour from the client side.

**Comment by pabigot** [comment]
Yes, my impression is the people creating the upstream interface you're wrapping don't really understand XML.  You might have better luck using an approach that doesn't use a validating XML processor.  I haven't used [generateDS](https://pypi.python.org/pypi/generateDS) for many years, but you could give it a try.

**Comment by rvalle** [comment]
Yes, I have been looking at generateDS.
In fact, seems to work in a fundamentally different way. It cherry-picks class members from the XML in the factorization process. Essentially, that means that it does not validate/enforce the XSD.

One could argue that this is wrong, not the point, etc. However, this wrong seems to nullify the wrong usage of XSDs here.

Thanks for the recommendation.
