### ISSUE TITLE
Update of code according to a change in the xsd scheme

### ISSUE THREAD

**Issue by gradzie** [pabigot/pyxb#99]
Hi,
I wrote in Python a writer and a reader for xml messages based on (1) an xsd schema provided by a third-party and (2) the Python bindings provided by the PyXB library.
I may receive in the future a new version of this xsd schema. 
How can I avoid hard-coding the implementation of any change in the xsd schema within my xml writer and reader? At least what is the simplest way to include a change in the xsd schema within an xml writer/reader?
Many thanks in advance for your help and advice.
Graziella

**Comment by pabigot** [comment]
I don't really have any suggestions, since it depends to a large degree on how the schema changes.

* Will the new schema use a different namespace? 
* Are changes simply providing explicit definitions for new elements and attributes that are already permitted through wildcards in the existing schema?
* Is use of the changes indicated through a version attribute in the document?

In the worst case (the answer to all three is "no") it may not be possible, or at least will be very ad hoc.

**Comment by gradzie** [comment]
Thank you very much for the quick reply.
1. Yes, the schema may use different namespaces for new/additional fields
basically.
2. Besides, new elements and attributes may not correspond to already
permitted ones through wildcards.
3. Yes a new version of the schema would be somehow indicated in the xsd.

In fact, my first understanding of the library was also that such an
automated update of xml writers/readers would not be possible. The library
focuses on bindings produced from a specific schemas but being quite junior
in Python I thought I may have missed some fucntionnalities...



2018-04-03 13:03 GMT+02:00 Peter A. Bigot <notifications@github.com>:

**Comment by pabigot** [comment]
If the namespace changes or an extension namespace is added you'll need to generate a new set of bindings for it.  When you load the bindings into the Python application the parsing should just work automatically as long as the instance documents identify the namespaces correctly.  Whatever the reader/writer needs to do that's specific to the content (anything you wrote yourself for the original schema) would have to be updated, but that probably couldn't be automated anyway.

**Comment by gradzie** [comment]
Thanks again Peter.
Indeed I think there is not much wiggle room to automate functions written
by myself... Generating automatic code is not the best option.
I was thinking about simply comparing xsd schemas to flag changes - do you
think the library could somehow do that?


2018-04-03 14:00 GMT+02:00 Peter A. Bigot <notifications@github.com>:

**Comment by pabigot** [comment]
It's possible: when the schema are parsed to generate the bindings, there is a complex data structure that contains all the information from it.  You could use that capability to read both schema and compare them.  Unless the schema are huge it'd probably be easier to compare them by hand.

**Comment by gradzie** [comment]
Thanks again - will explore this data structure!

**Comment by pabigot** [comment]
Closing since there is no bug here and no enhancements planned.
